import { AssessmentQuestion } from '../types';

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 1,
    question: "Have you noticed any unknown applications installed on your phone?",
    category: "Application Integrity",
    explanation: "Malware, spyware, or remote administration tools often disguise themselves as utilities or side-loaded APK packages without explicit consent.",
    factKey: "unknown_app",
    impactWeight: "HIGH",
  },
  {
    id: 2,
    question: "Is your phone battery draining unusually fast without a clear reason?",
    category: "Device Hardware",
    explanation: "Stealthy background processes, malicious socket connections, or unauthorized telemetry loops consume abnormal system power.",
    factKey: "battery_drain",
    impactWeight: "MEDIUM",
  },
  {
    id: 3,
    question: "Does your phone become unusually hot even when you are not using demanding applications?",
    category: "Device Hardware",
    explanation: "Continuous high CPU or GPU usage while idle is a classic symptom of concealed background tasks, cryptominers, or camera streaming.",
    factKey: "phone_hot",
    impactWeight: "MEDIUM",
  },
  {
    id: 4,
    question: "Have you received login alerts for accounts that you did not initiate?",
    category: "Authentication",
    explanation: "Foreign sign-in notifications from unfamiliar IP addresses or geographic regions suggest credential stuffing, token theft, or password compromise.",
    factKey: "unknown_login",
    impactWeight: "HIGH",
  },
  {
    id: 5,
    question: "Have messages, emails, or calls been sent from your device without your knowledge?",
    category: "Application Integrity",
    explanation: "Worms, SMS Trojans, and botnet clients transmit phishing payloads to contact lists or call premium-rate numbers autonomously.",
    factKey: "unauthorized_messages",
    impactWeight: "CRITICAL",
  },
  {
    id: 6,
    question: "Have you noticed any unauthorized financial transactions or suspicious payment activity?",
    category: "Financial & Transactions",
    explanation: "Direct financial leakage indicates critical account takeover, overlay banking Trojans, or compromised mobile wallets.",
    factKey: "unauthorized_transaction",
    impactWeight: "CRITICAL",
  },
  {
    id: 7,
    question: "Have you noticed unusual microphone, camera, or location access?",
    category: "System Permissions",
    explanation: "Privacy indicators (such as green/orange dots in Android/iOS) triggering randomly suggest active stalkerware or unauthorized sensor harvesting.",
    factKey: "unusual_permissions",
    impactWeight: "HIGH",
  },
  {
    id: 8,
    question: "Have you received suspicious OTP, password-reset, or account-recovery messages?",
    category: "Authentication",
    explanation: "Unsolicited 2FA codes indicate that an adversary has already guessed or acquired your primary credentials and is trying to bypass multi-factor verification.",
    factKey: "suspicious_otp",
    impactWeight: "HIGH",
  },
  {
    id: 9,
    question: "Has your phone recently become unusually slow or behaved abnormally?",
    category: "Device Hardware",
    explanation: "System UI freezing, reboot loops, spontaneous screen wakes, or ghost touches can reflect memory pressure from malicious injection hooks.",
    factKey: "abnormal_behavior",
    impactWeight: "MEDIUM",
  },
  {
    id: 10,
    question: "Do your accounts show unknown devices or sessions that you do not recognize?",
    category: "Authentication",
    explanation: "Active concurrent sessions originating from unknown browser agents or rogue hardware verify active unauthorized access to your account ecosystem.",
    factKey: "unknown_device",
    impactWeight: "CRITICAL",
  },
];

export const QUESTION_FACT_LABELS: Record<keyof import('../types').WorkingMemoryFacts, string> = {
  unknown_app: "Unknown Applications Detected",
  battery_drain: "Abnormal Battery Drain",
  phone_hot: "Thermal Spike While Idle",
  unknown_login: "Unrecognized Login Alerts",
  unauthorized_messages: "Outbound Messages Sent Without Consent",
  unauthorized_transaction: "Unauthorized Financial Activity",
  unusual_permissions: "Unusual Mic/Camera/Location Access",
  suspicious_otp: "Unsolicited OTP / Password Reset Requests",
  abnormal_behavior: "Device Sluggishness / System Instability",
  unknown_device: "Unrecognized Devices in Account Sessions",
};
