import React from 'react';
import { 
  X, 
  Download, 
  Printer, 
  Send, 
  ShieldCheck, 
  AlertTriangle, 
  FileText, 
  CheckCircle2, 
  Cpu, 
  Info,
  Calendar,
  Network
} from 'lucide-react';
import { IncidentReport } from '../types';
import { getRecommendedActions } from '../expertSystem/inferenceEngine';

interface IncidentReportModalProps {
  report: IncidentReport;
  onClose: () => void;
  onSubmitDemo: () => void;
}

export const IncidentReportModal: React.FC<IncidentReportModalProps> = ({
  report,
  onClose,
  onSubmitDemo,
}) => {
  const { inferenceResult, networkInfo } = report;
  const recommendations = getRecommendedActions(inferenceResult.severity);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadText = () => {
    const lines = [
      "==================================================================",
      "             CYBERSHIELD - CYBER INCIDENT REPORT                 ",
      "             Mobile Cyber Security Expert System                  ",
      "            ACADEMIC PROTOTYPE - DEMO/RESEARCH ONLY              ",
      "==================================================================",
      "",
      `INCIDENT TRACKING ID: ${report.incidentId}`,
      `TIMESTAMP:            ${report.timestamp}`,
      `ASSESSMENT TYPE:      ${report.assessmentType}`,
      `EVALUATION STATUS:    ${report.status}`,
      report.submissionRef ? `DEMO SUBMISSION REF:  ${report.submissionRef}` : "",
      "",
      "------------------------------------------------------------------",
      "EXPERT SYSTEM RISK CLASSIFICATION",
      "------------------------------------------------------------------",
      `RISK SCORE:           ${inferenceResult.normalizedScore} / 100`,
      `SEVERITY LEVEL:       ${inferenceResult.severity}`,
      `EVALUATION PARADIGM:  Forward-Chaining Propositional Inference`,
      `TRIGGERED RULES:      ${inferenceResult.triggeredRules.length} of 18 Production Rules`,
      "",
      "------------------------------------------------------------------",
      "NETWORK & TELEMETRY INFORMATION (SANDBOXED)",
      "------------------------------------------------------------------",
      `IP ADDRESS:           ${networkInfo.isMasked ? '192.168.1.xxx (Masked Demo)' : networkInfo.ip}`,
      `NETWORK STATUS:       ${networkInfo.status}`,
      `CONNECTION TYPE:      ${networkInfo.connectionType}`,
      `DETECTION TIMESTAMP:  ${networkInfo.detectionTime}`,
      `DISCLAIMER:           ${networkInfo.safetyNotice}`,
      "",
      "------------------------------------------------------------------",
      "DETECTED RISK INDICATORS (WORKING MEMORY)",
      "------------------------------------------------------------------",
      ...(inferenceResult.detectedIndicators.length > 0
        ? inferenceResult.detectedIndicators.map((ind) => `[*] ${ind}`)
        : ["[ ] No explicit threat indicators affirmed."]),
      "",
      "------------------------------------------------------------------",
      "EXPERT REASONING / FIRED PRODUCTION RULES",
      "------------------------------------------------------------------",
      ...(inferenceResult.triggeredRules.length > 0
        ? inferenceResult.triggeredRules.map((r) => 
            `[RULE ${r.ruleId}] ${r.ruleName} (+${r.riskContribution} pts)\n` +
            `  Category:    ${r.category}\n` +
            `  Condition:   ${r.conditionDescription}\n` +
            `  Rationale:   ${r.rationale}\n` +
            `  Action:      ${r.actionGuidance}\n`
          )
        : ["No specific production rules met firing preconditions."]),
      "",
      "------------------------------------------------------------------",
      "RECOMMENDED IMMEDIATE ACTIONS",
      "------------------------------------------------------------------",
      ...recommendations.map((rec, i) => `${i + 1}. [${rec.priority}] ${rec.title}\n   ${rec.desc}\n`),
      "",
      "==================================================================",
      "LEGAL & ACADEMIC NOTICE:",
      "This report was generated by an educational prototype expert system.",
      "It does not perform real-world hardware penetration, active network",
      "tracing, or transmission to emergency law enforcement services.",
      "=================================================================="
    ];

    const blob = new Blob([lines.filter(Boolean).join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `CyberIncidentReport-${report.incidentId}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/85 backdrop-blur-md overflow-y-auto">
      <div className="relative w-full max-w-4xl max-h-[92vh] flex flex-col rounded-2xl bg-slate-900 border border-slate-700 shadow-2xl shadow-cyan-950/40 text-slate-200 overflow-hidden">
        {/* Modal Top Bar */}
        <div className="flex items-center justify-between p-4 sm:p-5 border-b border-slate-800 bg-slate-950/80 shrink-0">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-cyan-950/80 border border-cyan-800/60 text-cyan-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold text-white tracking-tight">Cyber Incident Report</h3>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-amber-950/80 text-amber-300 border border-amber-800/60 font-semibold uppercase">
                  DEMO PROTOTYPE
                </span>
              </div>
              <p className="text-xs font-mono text-slate-400">
                REF: <span className="text-cyan-300 font-bold">{report.incidentId}</span>
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
            aria-label="Close Report Modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Scrollable Document Content */}
        <div className="p-6 sm:p-8 space-y-6 overflow-y-auto font-sans text-xs sm:text-sm print:text-black">
          {/* Document Header Header */}
          <div className="p-5 rounded-xl bg-slate-950/80 border border-slate-800 space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800 text-xs">
              <div className="space-y-1">
                <span className="text-slate-500 font-mono">INCIDENT ID</span>
                <div className="text-base font-bold font-mono text-cyan-400">
                  {report.incidentId}
                </div>
              </div>

              <div className="space-y-1 sm:text-right">
                <span className="text-slate-500 font-mono">GENERATION TIMESTAMP</span>
                <div className="font-mono text-slate-300">
                  {new Date(report.timestamp).toUTCString()}
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs font-mono">
              <div>
                <span className="text-slate-500 block">EVALUATION</span>
                <span className="text-slate-200 font-semibold">Rule-Based AI</span>
              </div>
              <div>
                <span className="text-slate-500 block">RISK SCORE</span>
                <span className="text-cyan-400 font-bold text-sm">
                  {inferenceResult.normalizedScore} / 100
                </span>
              </div>
              <div>
                <span className="text-slate-500 block">SEVERITY</span>
                <span className={`font-bold ${inferenceResult.severityColor.split(' ')[0]}`}>
                  {inferenceResult.severity}
                </span>
              </div>
              <div>
                <span className="text-slate-500 block">STATUS</span>
                <span className="text-emerald-400 font-semibold">
                  {report.status}
                </span>
              </div>
            </div>
          </div>

          {/* Network & Telemetry Section */}
          <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800 space-y-2 text-xs">
            <h4 className="font-bold text-white flex items-center gap-2">
              <Network className="w-4 h-4 text-blue-400" />
              <span>Network Context (Sandboxed)</span>
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 font-mono text-slate-400 pt-1">
              <div>IP: <span className="text-cyan-300">{networkInfo.isMasked ? '192.168.1.xxx (Masked)' : networkInfo.ip}</span></div>
              <div>Connection: <span className="text-slate-200">{networkInfo.connectionType}</span></div>
              <div>Status: <span className="text-emerald-400">{networkInfo.status}</span></div>
            </div>
            <p className="text-[11px] text-slate-500 pt-1">
              {networkInfo.safetyNotice}
            </p>
          </div>

          {/* Detected Indicators */}
          <div className="space-y-2">
            <h4 className="text-xs font-mono font-bold text-slate-400 uppercase tracking-wider">
              1. Observed Security Indicators
            </h4>
            <div className="flex flex-wrap gap-2">
              {inferenceResult.detectedIndicators.length > 0 ? (
                inferenceResult.detectedIndicators.map((ind, i) => (
                  <span
                    key={i}
                    className="px-2.5 py-1 rounded bg-slate-950 border border-slate-800 text-xs text-slate-300"
                  >
                    • {ind}
                  </span>
                ))
              ) : (
                <span className="text-xs text-slate-500 italic">No positive indicators recorded</span>
              )}
            </div>
          </div>

          {/* Triggered Rules Table */}
          <div className="space-y-2">
            <h4 className="text-xs font-mono font-bold text-slate-400 uppercase tracking-wider">
              2. Triggered Expert Rules & Inference Chain ({inferenceResult.triggeredRules.length})
            </h4>
            <div className="space-y-2">
              {inferenceResult.triggeredRules.map((tr) => (
                <div key={tr.ruleId} className="p-3 rounded-lg bg-slate-950 border border-slate-800 text-xs space-y-1">
                  <div className="flex items-center justify-between font-mono">
                    <span className="font-bold text-cyan-300">
                      [{tr.ruleId}] {tr.ruleName}
                    </span>
                    <span className="text-amber-400 font-bold">+{tr.riskContribution} pts</span>
                  </div>
                  <div className="font-mono text-slate-400 text-[11px]">
                    Condition: <code className="text-slate-300">{tr.conditionDescription}</code>
                  </div>
                  <p className="text-slate-400 text-[11px] leading-relaxed pt-0.5">
                    {tr.rationale}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Recommended Actions */}
          <div className="space-y-2">
            <h4 className="text-xs font-mono font-bold text-slate-400 uppercase tracking-wider">
              3. Recommended Mitigation Actions
            </h4>
            <div className="space-y-2">
              {recommendations.map((rec, i) => (
                <div key={i} className="p-3 rounded-lg bg-slate-950/70 border border-slate-800 text-xs space-y-1">
                  <div className="flex items-center justify-between">
                    <strong className="text-slate-200">
                      {i + 1}. {rec.title}
                    </strong>
                    <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-900 text-slate-300 border border-slate-800">
                      {rec.priority}
                    </span>
                  </div>
                  <p className="text-slate-400 text-xs leading-relaxed">
                    {rec.desc}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Academic Prototype Notice */}
          <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800/80 text-[11px] text-slate-500 space-y-1">
            <strong className="text-slate-400">Notice for Presentation & Evaluation:</strong>
            <p>
              This document was generated purely for academic evaluation in demonstration mode. No confidential data is stored outside the local client browser, and no law enforcement agency is notified by this software.
            </p>
          </div>
        </div>

        {/* Modal Bottom Action Controls */}
        <div className="flex flex-wrap items-center justify-between gap-3 p-4 sm:p-5 border-t border-slate-800 bg-slate-950/90 shrink-0">
          <div className="flex items-center gap-2">
            <button
              id="report-download-btn"
              onClick={handleDownloadText}
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold text-slate-200 bg-slate-900 hover:bg-slate-800 border border-slate-700 transition-colors"
            >
              <Download className="w-4 h-4 text-cyan-400" />
              <span>Download Report</span>
            </button>

            <button
              id="report-print-btn"
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold text-slate-200 bg-slate-900 hover:bg-slate-800 border border-slate-700 transition-colors"
            >
              <Printer className="w-4 h-4 text-slate-400" />
              <span>Print Report</span>
            </button>
          </div>

          <button
            id="report-submit-demo-btn"
            onClick={onSubmitDemo}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-xs font-bold text-slate-950 bg-gradient-to-r from-cyan-400 to-cyan-300 hover:from-cyan-300 hover:to-cyan-200 shadow-[0_0_15px_rgba(6,182,212,0.3)] transition-all"
          >
            <Send className="w-4 h-4 text-slate-950" />
            <span>Submit Report – Demo</span>
          </button>
        </div>
      </div>
    </div>
  );
};
